Traceback (most recent call last):
  File "C:\Users\muham\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\muham\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muham\AppData\Roaming\Python\Python311\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muham\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\muham\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 654, in async_setup_kernel
    yield
  File "C:\Users\muham\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\muham\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from google.colab import drive
drive.mount('/content/drive')



file_path = os.path.join('/content/drive', 'My Drive', 'Skripsi', 'Bahan', 'KalenderMakroekonomi2.html')
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[3], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mgoogle[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcolab[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m drive
[0;32m      2[0m drive[38;5;241m.[39mmount([38;5;124m'[39m[38;5;124m/content/drive[39m[38;5;124m'[39m)
[0;32m      6[0m file_path [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin([38;5;124m'[39m[38;5;124m/content/drive[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mMy Drive[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mSkripsi[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mBahan[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mKalenderMakroekonomi2.html[39m[38;5;124m'[39m)

[1;31mModuleNotFoundError[0m: No module named 'google.colab'

